flexix_prototype_controller_entity:
    resource: "@FlexixPrototypeControllerBundle/Resources/config/routing/entity.yml"
    prefix:   /


flexix_prototype_controller_extra:
    resource: "@FlexixPrototypeControllerBundle/Resources/config/routing/extra.yml"
    prefix:   /



        
