tabs:
    path: "{module}/{alias}/tabs/{id}"
    defaults: { _controller: "flexix_prototype_controller.extra_controller:tabsAction","action": "tabs", format: ~,id: null, module: null }
    methods:  [GET, POST]
    options:
        expose: true